import '../models/card.dart';

List<CardModule> cardsList = const [
  CardModule(
    id: 1,
    price: 30,
    location: 'Akchour , Chefchaouen',
    productImg: 'assets/popular/akchour1.png',
    productName: 'Akchour ',
  ),
  CardModule(
    id: 2,
    price: 4.50,
    location: 'Taghazout, Agadir',
    productImg: 'assets/popular/taghazout.jpg',
    productName: 'Taghazout',
  ),
  CardModule(
    id: 3,
    price: 5.00,
    location: 'Located 28 km from Azilal',
    productImg: 'assets/popular/BinelOuidane.jpg',
    productName: 'Bin el Ouidane lake',
  ),
  CardModule(
    id: 4,
    price: 5.00,
    location: 'Lalla Takerkoust is a town in Al Haouz Province, Marrakesh',
    productImg: 'assets/popular/Lallatakerkoust.jpeg',
    productName: 'Lalla Takerkoust',
  ),
  CardModule(
    id: 5,
    price: 10.00,
    location: 'Ouzoud Waterfalls, Azilal',
    productImg: 'assets/popular/OuzoudWaterfalls.jpg',
    productName: 'Ouzoud Waterfalls',
  ),
  CardModule(
    id: 6,
    price: 20.00,
    location: 'Dades Gorges, Tinghir',
    productImg: 'assets/popular/DadesGorges.jpg',
    productName: 'Dades Gorges',
  ),
  CardModule(
    id: 7,
    price: 7.00,
    location: 'Legzira Beach, Sidi Ifni',
    productImg: 'assets/popular/lagzira.jpg',
    productName: 'Legzira Beach',
  ),
  CardModule(
    id: 8,
    price: 15.00,
    location: 'Paradise Valley, Agadir',
    productImg: 'assets/popular/pardisevalley.png',
    productName: 'Paradise Valley',
  ),
  CardModule(
    id: 9,
    price: 25.00,
    location: 'Merzouga Desert, Merzouga',
    productImg: 'assets/popular/Merzouga.jpeg',
    productName: 'Merzouga Desert',
  ),
  CardModule(
    id: 11,
    price: 8.00,
    location: 'Ait Benhaddou, Ouarzazate',
    productImg: 'assets/popular/aitbenhaddou.jpg',
    productName: 'Ait Benhaddou',
  ),
  CardModule(
    id: 12,
    price: 5.00,
    location: 'Rif Mountains, Northern Morocco',
    productImg: 'assets/popular/rifmountains.jpg',
    productName: 'Rif Mountains',
  ),
  CardModule(
    id: 14,
    price: 6.00,
    location: 'Ourika Valley, High Atlas Mountains',
    productImg: 'assets/popular/ourikavalley.jpg',
    productName: 'Ourika Valley',
  ),
  CardModule(
    id: 17,
    price: 11.00,
    location: 'Ouarzazate, Film Studio',
    productImg: 'assets/popular/filmstudio.jpg',
    productName: 'Ouarzazate',
  ),
  CardModule(
    id: 18,
    price: 20.00,
    location: 'Atlas Mountains, Central Morocco',
    productImg: 'assets/popular/atlasmountains.jpg',
    productName: 'Atlas Mountains',
  ),
  CardModule(
    id: 19,
    price: 8.00,
    location: 'Volubilis, Near Meknes',
    productImg: 'assets/popular/volubilis.jpeg',
    productName: 'Meknes',
  ),
  CardModule(
    id: 20,
    price: 13.00,
    location: 'Citerne Portugaise , El Jadida',
    productImg: 'assets/popular/citernep.jpeg',
    productName: 'El Jadida',
  ),
  CardModule(
    id: 21,
    price: 16.00,
    location: 'Sidi Kaouki, Essaouira Province',
    productImg: 'assets/popular/sidikaouki.jpg',
    productName: 'Sidi Kaouki',
  ),
  CardModule(
    id: 22,
    price: 10.00,
    location: 'Moulay Idriss',
    productImg: 'assets/popular/moulayidriss.jpg',
    productName: 'Moulay Idriss Zerhoun',
  ),
  CardModule(
    id: 23,
    price: 12.00,
    location: 'Tafraoute, Anti-Atlas Mountains',
    productImg: 'assets/popular/tafraoute.jpg',
    productName: 'Tafraoute',
  ),
  CardModule(
    id: 24,
    price: 15.00,
    location: 'Ifrane, Middle Atlas Mountains',
    productImg: 'assets/ifran.jpg',
    productName: 'Ifrane',
  ),
];

